/********************************************************************
* ./src/g4numiCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/g4numiCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableg4numiCint();
extern void G__cpp_setup_inheritanceg4numiCint();
extern void G__cpp_setup_typetableg4numiCint();
extern void G__cpp_setup_memvarg4numiCint();
extern void G__cpp_setup_globalg4numiCint();
extern void G__cpp_setup_memfuncg4numiCint();
extern void G__cpp_setup_funcg4numiCint();
extern void G__set_cpp_environmentg4numiCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/data_t.hh"
#include "../include/hadmmtuple_t.hh"
#include "../include/zptuple_t.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__g4numiCintLN_TClass;
extern G__linked_taginfo G__g4numiCintLN_TBuffer;
extern G__linked_taginfo G__g4numiCintLN_TMemberInspector;
extern G__linked_taginfo G__g4numiCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__g4numiCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__g4numiCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__g4numiCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__g4numiCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__g4numiCintLN_data_t;
extern G__linked_taginfo G__g4numiCintLN_hadmmtuple_t;
extern G__linked_taginfo G__g4numiCintLN_zptuple_t;

/* STUB derived class for protected member access */
